#!/bin/sh
# =============================================================================
#  mwan3-setup.sh - dual-WAN failover for OpenWrt 25.12 on a Cudy R700
#
#    wan   port "wan"   main ISP    (existing interface, left as it is)
#    wan2  port "lan2"  backup ISP  (kept if it exists; otherwise created
#                                    and lan2 is taken out of the LAN bridge)
#
#  Copy it to the router and run it there as root:
#      scp -O mwan3-setup.sh root@192.168.1.1:/tmp/
#      ssh root@192.168.1.1
#      sh /tmp/mwan3-setup.sh          (-y = don't ask for confirmation)
#
#  Before you run it:
#    - the main ISP must be working (packages are downloaded first)
#    - your PC must be plugged into lan3, lan4 or lan5 - NOT lan2
#
#  Undo: sh /root/mwan3-backup-<date>/restore.sh
# =============================================================================

# ------------------------------- settings ------------------------------------
WAN_IF="wan"              # main ISP: existing logical interface
WANB_IF="wan2"            # backup ISP: logical interface (kept if it exists)
WANB_PORT="lan2"          # backup ISP: physical port

# used only if the backup interface doesn't exist yet and has to be created:
WANB_PROTO="dhcp"         # backup connection type: dhcp | static | pppoe
WANB_IPADDR=""            #   static: address, e.g. 192.168.8.2
WANB_NETMASK="255.255.255.0"
WANB_GATEWAY=""           #   static: gateway, e.g. 192.168.8.1
WANB_USERNAME=''          #   pppoe: login     (keep the single quotes)
WANB_PASSWORD=''          #   pppoe: password  (keep the single quotes)

WAN_METRIC=10             # route metrics - must differ, lower = preferred
WANB_METRIC=20

# DNS servers for the router, used on both WANs instead of the ISPs' ones.
# ISP resolvers often ignore queries that arrive through the other ISP, which
# breaks name resolution after a failover. "" = keep the ISP DNS servers.
PUBLIC_DNS="1.1.1.1 8.8.8.8"

# Health check: these hosts are pinged through each ISP separately
TRACK_IPS="1.1.1.1 8.8.8.8 9.9.9.9 208.67.222.222"
TRACK_RELIABILITY=2       # how many of them must answer for "link is up"
WAN_INTERVAL=5            # seconds between checks of the main ISP
WANB_INTERVAL=30          # backup is checked less often (less traffic on LTE)
TRACK_DOWN=3              # failed checks in a row -> offline      (~30 s)
TRACK_UP=5                # good checks in a row   -> online again (~30 s)

# What IPv4 traffic does:
#   failover   main ISP; backup only while the main one is down
#   balanced   connections spread over both ISPs
#   main_only | backup_only
DEFAULT_POLICY="failover"

# failover only:
# 1 = when the main ISP comes back, reset connections still running over the
#     backup so everything returns at once (running downloads/calls reconnect)
# 0 = only new connections use the main ISP, old ones finish on the backup
RETURN_TO_MAIN=1

# Hardware flow offloading on MT7621 is reported to break mwan3 (hanging
# HTTPS). 1 = switch it off if it is on; software offloading stays on.
DISABLE_HW_OFFLOAD=1
# -----------------------------------------------------------------------------

set -f                    # no filename globbing (port specs like "lan2:u*")
LOG=/tmp/mwan3-setup.log
ASSUME_YES=0

say()  { printf '%s\n' "$*"; printf '%s\n' "$*" >>"$LOG"; }
info() { say "[*] $*"; }
warn() { say "[!] $*"; }
die()  { say "[x] $*"; exit 1; }

for arg in "$@"; do
	case "$arg" in
		-y|--yes) ASSUME_YES=1 ;;
		-h|--help) sed -n '2,/^$/p' "$0"; exit 0 ;;
		*) echo "Unknown option '$arg' (use -y or -h)"; exit 1 ;;
	esac
done
: >"$LOG"

# ------------------------------- functions -----------------------------------

# one mwan3 interface section: <interface> <check interval> <flush events>
mwan3_iface() {
	local ip ev
	cat <<EOF

config interface '$1'
	option enabled '1'
	option family 'ipv4'
	option initial_state 'offline'
	option reliability '$TRACK_RELIABILITY'
	option timeout '2'
	option interval '$2'
	option failure_interval '2'
	option recovery_interval '5'
	option down '$TRACK_DOWN'
	option up '$TRACK_UP'
EOF
	for ip in $TRACK_IPS; do printf "\tlist track_ip '%s'\n" "$ip"; done
	for ev in $3; do printf "\tlist flush_conntrack '%s'\n" "$ev"; done
}

gen_mwan3() {
	# main ISP goes offline: drop its dead connections so they reopen via backup
	local flush="disconnected"
	[ "$DEFAULT_POLICY" = failover ] && [ "$RETURN_TO_MAIN" = 1 ] &&
		flush="disconnected connected"
	cat <<EOF
# Generated by mwan3-setup.sh on $(date)
# $WAN_IF = main ISP, $WANB_IF = backup ISP (port $WANB_PORT)

config globals 'globals'
	option mmx_mask '0x3F00'
EOF
	mwan3_iface "$WAN_IF" "$WAN_INTERVAL" "$flush"
	mwan3_iface "$WANB_IF" "$WANB_INTERVAL" ""
	cat <<EOF

config member 'main_m1'
	option interface '$WAN_IF'
	option metric '1'
	option weight '1'

config member 'backup_m1'
	option interface '$WANB_IF'
	option metric '1'
	option weight '1'

config member 'backup_m2'
	option interface '$WANB_IF'
	option metric '2'
	option weight '1'

config policy 'failover'
	list use_member 'main_m1'
	list use_member 'backup_m2'
	option last_resort 'default'

config policy 'balanced'
	list use_member 'main_m1'
	list use_member 'backup_m1'
	option last_resort 'default'

config policy 'main_only'
	list use_member 'main_m1'
	option last_resort 'unreachable'

config policy 'backup_only'
	list use_member 'backup_m1'
	option last_resort 'unreachable'
EOF
	if [ "$DEFAULT_POLICY" = balanced ]; then
		cat <<EOF

config rule 'https'
	option proto 'tcp'
	option dest_port '443'
	option family 'ipv4'
	option sticky '1'
	option use_policy 'balanced'
EOF
	fi
	cat <<EOF

config rule 'default_rule_v4'
	option dest_ip '0.0.0.0/0'
	option family 'ipv4'
	option use_policy '$DEFAULT_POLICY'
EOF
}

# network address: net_of 192.168.1.77 24 -> 192.168.1.0
net_of() {
	local IFS=. p="$2" o out=""
	for o in $1; do
		if [ "$p" -le 0 ]; then
			o=0
		elif [ "$p" -lt 8 ]; then
			o=$((o & (0xff << (8 - p)) & 0xff))
		fi
		out="$out${out:+.}$o"
		p=$((p - 8))
	done
	echo "$out"
}

# check_overlap <name> <ip/prefix> <name> <ip/prefix>
check_overlap() {
	local p
	[ -n "$2" ] && [ -n "$4" ] || return 0
	p=${2#*/}
	[ "${4#*/}" -lt "$p" ] && p=${4#*/}
	[ "$(net_of "${2%/*}" "$p")" = "$(net_of "${4%/*}" "$p")" ] || return 0
	warn "SUBNET CONFLICT: $1 $2 overlaps $3 $4 - routing can't work like this."
	warn "  Give the router's LAN (or the ISP router in front of it) another subnet."
}

wait_up() {   # <interface> <seconds>
	local t=0
	while [ "$t" -lt "$2" ]; do
		network_flush_cache
		network_is_up "$1" && return 0
		sleep 1
		t=$((t + 1))
	done
	return 1
}

row() { say "$(printf '  %-16s %s' "$1" "$2")"; }

# config_foreach callbacks
PORT_USERS=""
V6_IFS=""
scan_iface() {            # other users of the port, IPv6 side of both ISPs
	local dev proto
	[ "$1" = "$WANB_IF" ] && return
	config_get dev "$1" device
	config_get proto "$1" proto
	if [ "$proto" = dhcpv6 ]; then    # e.g. wan6 on wan, wan62 on lan2
		case "$dev" in
			"$WAN_DEV"|"@$WAN_IF"|"$WANB_PORT"|"@$WANB_IF")
				V6_IFS="$V6_IFS $1"
				return
				;;
		esac
	fi
	case "$dev" in
		"$WANB_PORT"|"$WANB_PORT".*) PORT_USERS="$PORT_USERS $1" ;;
	esac
}

LAN_PORTS=""
find_bridge_ports() {     # ports that stay in the bridge with the port
	local type ports p hit=0 rest=""
	config_get type "$1" type
	[ "$type" = bridge ] || return
	config_get ports "$1" ports
	for p in $ports; do
		if [ "$p" = "$WANB_PORT" ]; then hit=1; else rest="$rest $p"; fi
	done
	[ "$hit" = 1 ] && LAN_PORTS="$LAN_PORTS$rest"
}

remove_port() {           # take the port out of bridges and bridge VLANs
	local ports p keep="" hit=0
	config_get ports "$1" ports
	for p in $ports; do
		case "$p" in
			"$WANB_PORT"|"$WANB_PORT":*) hit=1 ;;
			*) keep="$keep $p" ;;
		esac
	done
	[ "$hit" = 1 ] || return 0
	# rebuild the list (also works if it was saved as one string)
	uci -q delete "network.$1.ports"
	for p in $keep; do uci add_list "network.$1.ports=$p"; done
	info "  $WANB_PORT removed from $(uci -q get "network.$1.name" || uci -q get "network.$1.device")"
}

WAN_ZONE=""
WAN_ZONE_NAME=""
WAN_ZONE_NETS=""
find_wan_zone() {         # firewall zone that holds the main WAN
	local nets n
	config_get nets "$1" network
	for n in $nets; do
		[ "$n" = "$WAN_IF" ] || continue
		WAN_ZONE="$1"
		WAN_ZONE_NETS="$nets"
		config_get WAN_ZONE_NAME "$1" name
	done
}

show_plan() {
	echo
	echo "Planned changes:"
	if [ "$PKGS_PRESENT" = 1 ]; then
		echo "  - mwan3 and luci-app-mwan3: already installed"
	else
		echo "  - install mwan3 and luci-app-mwan3 ($PKG)"
	fi
	[ -n "$LAN_PORTS" ] &&
		echo "  - take $WANB_PORT out of the LAN bridge (LAN keeps:$LAN_PORTS)"
	if [ "$WANB_EXISTS" = 1 ]; then
		echo "  - keep interface '$WANB_IF' on $WANB_PORT as it is ($WANB_PROTO_NOW), set metric $WANB_METRIC"
	else
		echo "  - new interface '$WANB_IF' on $WANB_PORT: $WANB_PROTO, metric $WANB_METRIC"
	fi
	echo "  - '$WAN_IF': metric $WAN_METRIC"
	echo "  - $FW_NOTE"
	if [ -n "$PUBLIC_DNS" ]; then
		echo "  - router DNS $PUBLIC_DNS instead of the ISPs' (on $WAN_IF $WANB_IF$V6_IFS)"
	else
		echo "  - router DNS: unchanged (from the ISPs)"
	fi
	[ "$HW_OFFLOAD" = 1 ] &&
		echo "  - hardware flow offloading off (software offloading stays on)"
	echo "  - mwan3 policy '$DEFAULT_POLICY', health check: ping $TRACK_IPS"
	echo "  - current config is saved to $BACKUP_DIR"
	echo
	echo "Your PC must NOT be plugged into $WANB_PORT - you would lose access to the router."
	echo
}

# -------------------------------- checks -------------------------------------
[ -f /etc/openwrt_release ] || die "This is not OpenWrt."
[ -w /etc/config/network ] || die "Run this script as root."
. /etc/openwrt_release
. /lib/functions.sh
. /lib/functions/network.sh

MODEL="$(cat /tmp/sysinfo/model 2>/dev/null)"
info "Router: ${MODEL:-unknown}, $DISTRIB_DESCRIPTION"
case "$DISTRIB_RELEASE" in
	25.12*|SNAPSHOT) ;;
	*) warn "Written for OpenWrt 25.12, this is $DISTRIB_RELEASE - continuing anyway." ;;
esac
case "$MODEL" in
	*R700*) ;;
	*) warn "Written for the Cudy R700 - check that the port names fit this router." ;;
esac

case "$DEFAULT_POLICY" in
	failover|balanced|main_only|backup_only) ;;
	*) die "DEFAULT_POLICY must be failover, balanced, main_only or backup_only." ;;
esac
case "$WANB_IF" in
	""|*[!A-Za-z0-9_]*) die "WANB_IF may only contain letters, digits and '_'." ;;
esac
[ ${#WANB_IF} -le 9 ] || die "WANB_IF must be 9 characters or less."

WANB_EXISTS=0
if [ "$(uci -q get "network.$WANB_IF")" = interface ]; then
	WANB_DEV_NOW="$(uci -q get "network.$WANB_IF.device")"
	[ "$WANB_DEV_NOW" = "$WANB_PORT" ] ||
		die "Interface '$WANB_IF' exists but uses '${WANB_DEV_NOW:-no device}', not $WANB_PORT - adjust WANB_IF or WANB_PORT."
	WANB_EXISTS=1
	WANB_PROTO_NOW="$(uci -q get "network.$WANB_IF.proto")"
else
	case "$WANB_PROTO" in
		dhcp) ;;
		static) [ -n "$WANB_IPADDR" ] && [ -n "$WANB_GATEWAY" ] ||
			die "WANB_PROTO=static needs WANB_IPADDR and WANB_GATEWAY." ;;
		pppoe) [ -n "$WANB_USERNAME" ] && [ -n "$WANB_PASSWORD" ] ||
			die "WANB_PROTO=pppoe needs WANB_USERNAME and WANB_PASSWORD." ;;
		*) die "WANB_PROTO must be dhcp, static or pppoe." ;;
	esac
fi
[ "$WAN_METRIC" != "$WANB_METRIC" ] || die "WAN_METRIC and WANB_METRIC must differ."
n=0
for ip in $TRACK_IPS; do n=$((n + 1)); done
[ "$n" -ge "$TRACK_RELIABILITY" ] ||
	die "TRACK_RELIABILITY is larger than the number of TRACK_IPS."

[ "$(uci -q get "network.$WAN_IF")" = interface ] ||
	die "Interface '$WAN_IF' does not exist in /etc/config/network."
[ -d "/sys/class/net/$WANB_PORT" ] ||
	die "Port '$WANB_PORT' not found. Network devices: $(ls /sys/class/net | tr '\n' ' ')"

PENDING="$(for c in network firewall dhcp mwan3; do uci -q changes "$c"; done)"
[ -z "$PENDING" ] || die "There are uncommitted uci changes - commit or revert them first:
$PENDING"

if command -v apk >/dev/null 2>&1; then
	PKG=apk; PKG_DEL="apk del"
elif command -v opkg >/dev/null 2>&1; then
	PKG=opkg; PKG_DEL="opkg remove"
else
	die "No package manager (apk/opkg) found."
fi

WAN_DEV="$(uci -q get "network.$WAN_IF.device")"
config_load network
config_foreach scan_iface interface
config_foreach find_bridge_ports device
[ -z "$PORT_USERS" ] || die "Port $WANB_PORT is already used by interface(s):$PORT_USERS -" \
	"set WANB_IF to that name to use it as the backup, or delete it in LuCI."

config_load firewall
config_foreach find_wan_zone zone
[ -n "$WAN_ZONE" ] || die "No firewall zone contains the interface '$WAN_IF'."
case " $WAN_ZONE_NETS " in
	*" $WANB_IF "*) FW_NOTE="firewall: '$WANB_IF' is already in zone '$WAN_ZONE_NAME'" ;;
	*) FW_NOTE="firewall: add '$WANB_IF' to zone '$WAN_ZONE_NAME'" ;;
esac

PKGS_PRESENT=0
[ -x /usr/sbin/mwan3 ] && [ -f /usr/share/luci/menu.d/luci-app-mwan3.json ] &&
	PKGS_PRESENT=1

HW_OFFLOAD=0
[ "$DISABLE_HW_OFFLOAD" = 1 ] &&
	[ "$(uci -q get 'firewall.@defaults[0].flow_offloading_hw')" = 1 ] && HW_OFFLOAD=1

BACKUP_DIR="/root/mwan3-backup-$(date +%Y%m%d-%H%M%S)"
show_plan | tee -a "$LOG"

if [ "$ASSUME_YES" != 1 ]; then
	printf 'Continue? [y/N] '
	ans=""
	read -r ans 2>/dev/null </dev/tty || echo
	case "$ans" in
		y|Y|yes|YES) ;;
		*) die "Aborted - nothing was changed. (-y runs without this question)" ;;
	esac
fi

# -------------------------------- backup -------------------------------------
mkdir -p "$BACKUP_DIR" || die "Cannot create $BACKUP_DIR."
for c in network firewall dhcp mwan3; do
	[ -f "/etc/config/$c" ] && cp -p "/etc/config/$c" "$BACKUP_DIR/"
done
cat >"$BACKUP_DIR/restore.sh" <<EOF
#!/bin/sh
# Undoes mwan3-setup.sh: puts back the configuration saved on $(date)
/etc/init.d/mwan3 stop 2>/dev/null
/etc/init.d/mwan3 disable 2>/dev/null
for c in network firewall dhcp mwan3; do
	[ -f "$BACKUP_DIR/\$c" ] && cp -p "$BACKUP_DIR/\$c" "/etc/config/\$c"
done
/etc/init.d/network reload
/etc/init.d/firewall reload
/etc/init.d/dnsmasq reload
echo "Configuration restored, mwan3 disabled. To remove it: $PKG_DEL luci-app-mwan3 mwan3"
EOF
chmod +x "$BACKUP_DIR/restore.sh"
info "Current configuration saved to $BACKUP_DIR"

# ------------------------------- packages ------------------------------------
if [ "$PKGS_PRESENT" = 1 ]; then
	info "mwan3 and luci-app-mwan3 are already installed."
else
	FREE_KB="$(df -k /overlay 2>/dev/null | awk 'NR == 2 { print $4 }')"
	[ -n "$FREE_KB" ] && [ "$FREE_KB" -lt 2048 ] &&
		warn "Only $FREE_KB KB free in /overlay - the packages may not fit."
	info "Installing mwan3 and luci-app-mwan3..."
	if [ "$PKG" = apk ]; then
		apk update || die "apk update failed - is the main ISP working? Nothing was changed."
		apk add mwan3 || die "Installing mwan3 failed. Nothing was changed."
		apk add luci-app-mwan3 || warn "luci-app-mwan3 did not install - mwan3 works without it (no web UI)."
	else
		opkg update || die "opkg update failed - is the main ISP working? Nothing was changed."
		opkg install mwan3 || die "Installing mwan3 failed. Nothing was changed."
		opkg install luci-app-mwan3 || warn "luci-app-mwan3 did not install - mwan3 works without it (no web UI)."
	fi
fi
/etc/init.d/mwan3 stop >/dev/null 2>&1

# -------------------------------- network ------------------------------------
info "Configuring network..."
config_load network
config_foreach remove_port device
config_foreach remove_port bridge-vlan

if [ "$WANB_EXISTS" = 1 ]; then
	info "  keeping the existing interface '$WANB_IF'"
else
	uci set "network.$WANB_IF=interface"
	uci set "network.$WANB_IF.device=$WANB_PORT"
	uci set "network.$WANB_IF.proto=$WANB_PROTO"
	case "$WANB_PROTO" in
		static)
			uci set "network.$WANB_IF.ipaddr=$WANB_IPADDR"
			uci set "network.$WANB_IF.netmask=$WANB_NETMASK"
			uci set "network.$WANB_IF.gateway=$WANB_GATEWAY"
			;;
		pppoe)
			uci set "network.$WANB_IF.username=$WANB_USERNAME"
			uci set "network.$WANB_IF.password=$WANB_PASSWORD"
			uci set "network.$WANB_IF.ipv6=0"
			;;
	esac
	info "  interface '$WANB_IF' created on $WANB_PORT"
fi
uci set "network.$WANB_IF.metric=$WANB_METRIC"
uci set "network.$WAN_IF.metric=$WAN_METRIC"

if [ -n "$PUBLIC_DNS" ]; then
	for i in "$WAN_IF" "$WANB_IF"; do
		uci -q delete "network.$i.dns"
		for d in $PUBLIC_DNS; do uci add_list "network.$i.dns=$d"; done
		[ "$(uci -q get "network.$i.proto")" = static ] || uci set "network.$i.peerdns=0"
	done
	# the ISPs' IPv6 resolvers (wan6, wan62, ...) have the same problem
	for i in $V6_IFS; do uci set "network.$i.peerdns=0"; done
fi

if [ -f /etc/config/dhcp ]; then      # no DHCP server on the backup port
	uci set "dhcp.$WANB_IF=dhcp"
	uci set "dhcp.$WANB_IF.interface=$WANB_IF"
	uci set "dhcp.$WANB_IF.ignore=1"
fi

# -------------------------------- firewall -----------------------------------
info "Configuring firewall..."
uci -q delete "firewall.$WAN_ZONE.network"
for n in $WAN_ZONE_NETS; do
	[ "$n" = "$WANB_IF" ] || uci add_list "firewall.$WAN_ZONE.network=$n"
done
uci add_list "firewall.$WAN_ZONE.network=$WANB_IF"
if [ "$HW_OFFLOAD" = 1 ]; then
	info "Turning hardware flow offloading off..."
	uci set 'firewall.@defaults[0].flow_offloading_hw=0'
	uci set 'firewall.@defaults[0].flow_offloading=1'
fi

# --------------------------------- mwan3 -------------------------------------
info "Writing /etc/config/mwan3..."
uci -q revert mwan3
gen_mwan3 >/etc/config/mwan3
if ! uci -q show mwan3 >/dev/null; then
	for c in network firewall dhcp; do uci -q revert "$c"; done
	[ -f "$BACKUP_DIR/mwan3" ] && cp -p "$BACKUP_DIR/mwan3" /etc/config/mwan3
	die "The generated /etc/config/mwan3 is invalid - nothing was applied."
fi
# re-add the rule kept by dante-via-backup.sh, if that is installed
[ -x /usr/sbin/mwan3-backup-src ] && /usr/sbin/mwan3-backup-src --no-restart

uci commit network
uci commit firewall
[ -f /etc/config/dhcp ] && uci commit dhcp

# --------------------------------- apply -------------------------------------
trap '' HUP PIPE          # keep going if the SSH session drops during reload
info "Reloading network - the SSH session may freeze for a few seconds..."
/etc/init.d/network reload >>"$LOG" 2>&1
sleep 3
wait_up "$WAN_IF" 30 || warn "'$WAN_IF' is not up (yet)."
wait_up "$WANB_IF" 30 || warn "'$WANB_IF' is not up - is the backup ISP plugged into $WANB_PORT?"

info "Reloading firewall and DNS..."
/etc/init.d/firewall reload >>"$LOG" 2>&1
/etc/init.d/dnsmasq reload >>"$LOG" 2>&1

info "Starting mwan3..."
/etc/init.d/mwan3 enable
/etc/init.d/mwan3 restart >>"$LOG" 2>&1 || warn "mwan3 did not start cleanly - see $LOG"

info "Waiting for the first health checks (up to 60 s)..."
t=0
while [ "$t" -lt 60 ]; do
	mwan3 interfaces 2>/dev/null | grep -q "interface $WAN_IF is online.*(online" && break
	sleep 5
	t=$((t + 5))
done

# -------------------------------- report -------------------------------------
network_flush_cache
network_get_subnet S_LAN lan
network_get_subnet S_WAN "$WAN_IF"
network_get_subnet S_WANB "$WANB_IF"
network_get_gateway G_WAN "$WAN_IF"
network_get_gateway G_WANB "$WANB_IF"
say ""
row "LAN" "${S_LAN:--}"
row "$WAN_IF (main)" "${S_WAN:-no address}  gateway ${G_WAN:--}"
row "$WANB_IF (backup)" "${S_WANB:-no address}  gateway ${G_WANB:--}"
check_overlap "LAN" "$S_LAN" "$WAN_IF" "$S_WAN"
check_overlap "LAN" "$S_LAN" "$WANB_IF" "$S_WANB"
check_overlap "$WAN_IF" "$S_WAN" "$WANB_IF" "$S_WANB"
say ""
mwan3 interfaces 2>&1 | tee -a "$LOG"

cat <<EOF | tee -a "$LOG"

Done. Log: $LOG
  Web UI         Status -> MultiWAN Manager, Network -> MultiWAN Manager
  Status         mwan3 status
  Public IP      wget -qO- http://api.ipify.org; echo
  Test backup    mwan3 use $WANB_IF ping -c 3 1.1.1.1
  Live log       logread -f -e mwan3
  Failover test  unplug the main ISP cable (or its modem's uplink) and watch
                 the log: switching over and back takes about 30 s each.
  Undo           sh $BACKUP_DIR/restore.sh
EOF
